version: "3.9"
services:
  postgres:
    container_name: smartparkingconfig-db
    image: postgres:latest
    environment:
      POSTGRES_DB: smartparkingconfig
      POSTGRES_USER: smartparkingconfig
      POSTGRES_PASSWORD: smartparkingconfig
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U smartparkingconfig']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - smartparkingconfig-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - smartparkingconfig-pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

  smartparkingconfig-db-keycloak:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: 'keycloak'
      POSTGRES_USER: 'keycloak'
      POSTGRES_PASSWORD: 'keycloak'
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U keycloak'] 
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - smartparkingconfig-keycloak-db:/var/lib/postgresql/data
    networks:
      - backend

  smartparkingconfig-keycloak:
    image: quay.io/keycloak/keycloak
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    depends_on:
      smartparkingconfig-db-keycloak:
        condition: service_healthy
    restart: on-failure
    environment:
      KC_DB_URL: jdbc:postgresql://smartparkingconfig-db-keycloak:5432/keycloak
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth/
    command: start-dev --import-realm
    ports:
      - '8080:8080'
    networks:
      - backend


networks:
  backend:

volumes:
  smartparkingconfig-db:
  smartparkingconfig-pgadmin:
  smartparkingconfig-keycloak-db:

